const TrussExample = {
    "matProp": [{
            "ele": "ele1",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele2",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele3",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele4",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele5",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele6",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele7",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele8",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele9",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele10",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele11",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele12",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele13",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele14",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele15",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele16",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele17",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele18",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele19",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele20",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele21",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele22",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele23",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele24",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele25",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele26",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele27",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele28",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele29",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele30",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele31",
            "E": 10000,
            "A": 19.625
        }, {
            "ele": "ele32",
            "E": 10000,
            "A": 19.625
        }
    ],
    "nodalCoords": [{
            "id": "node1",
            "x": -200,
            "y": 0,
            "z": 0
        }, {
            "id": "node2",
            "x": -100,
            "y": 100,
            "z": 0
        }, {
            "id": "node3",
            "x": 0,
            "y": 100,
            "z": 0
        }, {
            "id": "node4",
            "x": 100,
            "y": 100,
            "z": 0
        }, {
            "id": "node5",
            "x": 200,
            "y": 0,
            "z": 0
        }, {
            "id": "node6",
            "x": 100,
            "y": 0,
            "z": 0
        }, {
            "id": "node7",
            "x": 0,
            "y": 0,
            "z": 0
        }, {
            "id": "node8",
            "x": -100,
            "y": 0,
            "z": 0
        }, {
            "id": "node9",
            "x": -200,
            "y": 0,
            "z": -100
        }, {
            "id": "node10",
            "x": -100,
            "y": 100,
            "z": -100
        }, {
            "id": "node11",
            "x": 0,
            "y": 100,
            "z": -100
        }, {
            "id": "node12",
            "x": 100,
            "y": 100,
            "z": -100
        }, {
            "id": "node13",
            "x": 200,
            "y": 0,
            "z": -100
        }, {
            "id": "node14",
            "x": 100,
            "y": 0,
            "z": -100
        }, {
            "id": "node15",
            "x": 0,
            "y": 0,
            "z": -100
        }, {
            "id": "node16",
            "x": -100,
            "y": 0,
            "z": -100
        }
    ],
    "connectivity": [{
            "id": "ele1",
            "i": "node1",
            "j": "node2"
        }, {
            "id": "ele2",
            "i": "node2",
            "j": "node3"
        }, {
            "id": "ele3",
            "i": "node3",
            "j": "node4"
        }, {
            "id": "ele4",
            "i": "node4",
            "j": "node5"
        }, {
            "id": "ele5",
            "i": "node5",
            "j": "node6"
        }, {
            "id": "ele6",
            "i": "node6",
            "j": "node7"
        }, {
            "id": "ele7",
            "i": "node7",
            "j": "node8"
        }, {
            "id": "ele8",
            "i": "node8",
            "j": "node1"
        }, {
            "id": "ele9",
            "i": "node8",
            "j": "node3"
        }, {
            "id": "ele10",
            "i": "node2",
            "j": "node7"
        }, {
            "id": "ele11",
            "i": "node3",
            "j": "node6"
        }, {
            "id": "ele12",
            "i": "node7",
            "j": "node4"
        }, {
            "id": "ele13",
            "i": "node1",
            "j": "node9"
        }, {
            "id": "ele14",
            "i": "node2",
            "j": "node10"
        }, {
            "id": "ele15",
            "i": "node3",
            "j": "node11"
        }, {
            "id": "ele16",
            "i": "node4",
            "j": "node12"
        }, {
            "id": "ele17",
            "i": "node5",
            "j": "node13"
        }, {
            "id": "ele18",
            "i": "node6",
            "j": "node14"
        }, {
            "id": "ele19",
            "i": "node7",
            "j": "node15"
        }, {
            "id": "ele20",
            "i": "node8",
            "j": "node16"
        }, {
            "id": "ele21",
            "i": "node9",
            "j": "node10"
        }, {
            "id": "ele22",
            "i": "node10",
            "j": "node11"
        }, {
            "id": "ele23",
            "i": "node11",
            "j": "node12"
        }, {
            "id": "ele24",
            "i": "node12",
            "j": "node13"
        }, {
            "id": "ele25",
            "i": "node13",
            "j": "node14"
        }, {
            "id": "ele26",
            "i": "node14",
            "j": "node15"
        }, {
            "id": "ele27",
            "i": "node15",
            "j": "node16"
        }, {
            "id": "ele28",
            "i": "node16",
            "j": "node9"
        }, {
            "id": "ele29",
            "i": "node16",
            "j": "node11"
        }, {
            "id": "ele30",
            "i": "node10",
            "j": "node15"
        }, {
            "id": "ele31",
            "i": "node11",
            "j": "node14"
        }, {
            "id": "ele32",
            "i": "node15",
            "j": "node12"
        }
    ],
    "forceVector": [{
            "node": "node2",
            "u1": 0,
            "u2": -25000,
            "u3": 0
        }, {
            "node": "node12",
            "u1": 0,
            "u2": -15000,
            "u3": 0
        }
    ],
    "boundaryConditions": [{
            "node": "node1",
            "u1": true,
            "u2": true,
            "u3": true
        }, {
            "node": "node5",
            "u1": true,
            "u2": true,
            "u3": true
        }, {
            "node": "node9",
            "u1": true,
            "u2": true,
            "u3": true
        }, {
            "node": "node13",
            "u1": true,
            "u2": true,
            "u3": true
        }
    ],
    "stresses": []
};

export default TrussExample;
